@startuml

class EmailDetails {
    private String recipient;
    private String msgBody;
    private String subject;
    private String attachment;
}

class EmailSender {
    MultipartFile[] file;
    String to;
    String[] cc;
    String subject;
    String body;
}

@enduml