apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ecommerce
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: wait-for-discovery
          image: busybox
          command: ["sh", "-c", "until nc -z discovery-service 8761; do sleep 3; done"]
        - name: wait-for-keycloak
          image: busybox
          command: ["sh", "-c", "until nc -z keycloak 8080; do sleep 5; done"]
      containers:
        - name: auth-service
          image: ghcr.io/hoangtien2k3/ecommerce-microservices/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/authservice
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 120
            periodSeconds: 15
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecommerce
spec:
  selector:
    app: auth-service
  ports:
    - port: 8088
      targetPort: 8088
