apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: ecommerce
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: ghcr.io/hoangtien2k3/ecommerce-microservices/discovery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: EUREKA_URI
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 0
            periodSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: ecommerce
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
