apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: ecommerce
  labels:
    app: media-service
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ["sh", "-c", "until nc -z postgres 5432; do sleep 3; done"]
        - name: wait-for-minio
          image: busybox
          command: ["sh", "-c", "until nc -z minio 9000; do sleep 3; done"]
      containers:
        - name: media-service
          image: ghcr.io/hoangtien2k3/media-service:sha-374ea13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mediaservice
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: ecommerce
spec:
  selector:
    app: media-service
  ports:
    - port: 8083
      targetPort: 8083
