apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: ecommerce
  labels:
    app: media-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ["sh", "-c", "until nc -z postgres 5432; do sleep 3; done"]
        - name: wait-for-rustfs
          image: busybox
          command: ["sh", "-c", "until nc -z rustfs 9000; do sleep 3; done"]
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: media-service
          image: ghcr.io/hoangtien2k3/media-service:latest
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            privileged: false
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mediaservice
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_ACCESS_KEY
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_SECRET_KEY
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: media-service
  ports:
    - port: 8083
      targetPort: 8083
