apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  namespace: ecommerce
  labels:
    app: rating-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ["sh", "-c", "until nc -z postgres 5432; do sleep 3; done"]
      containers:
        - name: rating-service
          image: ghcr.io/hoangtien2k3/rating-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ratingservice
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 120
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: ecommerce
spec:
  selector:
    app: rating-service
  ports:
    - port: 8089
      targetPort: 8089
