apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: ecommerce
  labels:
    app: admin
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: admin
          image: ghcr.io/hoangtien2k3/frontend-admin:latest
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            privileged: false
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
          startupProbe:
            httpGet:
              path: /
              port: 3001
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - port: 3001
      targetPort: 3001
