server:
  port: 8081

spring:
  application:
    name: FAVOURITE-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/favouriteservice
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: false
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://identity/realms/hoangtien2k3}

  # ZIPKIN & SLEUTH
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  file:
    name: src/main/resources/script/prod_log.log
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
        boot:
          autoconfigure:
            data:
              rest: INFO
              jdbc: INFO
            orm: INFO
