
@startuml
package "Entities" {

  class Order extends AbstractMappedEntity {
    +orderId: Integer
    +orderDate: LocalDateTime
    +orderDesc: String
    +orderFee: Double
    --
  }

  class Cart extends AbstractMappedEntity {
    +cartId: Integer
    +userId: Integer
    --
  }

  abstract class AbstractMappedEntity implements Serializable {

      @Serial
      private static final long serialVersionUID = 1L;

      private Instant createdAt;

      private Instant updatedAt;

  }

}

Order --|> Cart : includes

@enduml


