apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "ecommerce@!@#"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: ecommerce
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "ecommerce@!@#"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ecommerce
type: Opaque
stringData:
  REDIS_PASSWORD: "ecommerce@!@#"
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
  namespace: ecommerce
type: Opaque
stringData:
  STORAGE_ACCESS_KEY: "test"
  STORAGE_SECRET_KEY: "test"
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: ecommerce
type: Opaque
stringData:
  ELASTIC_PASSWORD: "ecommerce@!@#"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: ecommerce
type: Opaque
stringData:
  MAIL_USERNAME: "hoangtien2k3qx1@gmail.com"
  MAIL_PASSWORD: "uvbskgpuchmgtlbp"
