@startuml

class User {

    @Id
    private Long id;

    private String name;

    private String username;

    private String email;

    private String password;

    private String avatar;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "user_role",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private Set<Role> roles = new HashSet<>();

}

class Role {

    @Id
    private Long id;

    private RoleName name;

}



@enduml