server:
  servlet:
    context-path: /common-library

spring:
  application:
    name: common-library
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://identity/realms/hoangtien2k3}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  oauthflow:
    authorization-url: ${JWT_AUTH_URL:http://identity/realms/hoangtien2k3/protocol/openid-connect/auth}
    token-url: ${JWT_TOKEN_URL:http://identity/realms/hoangtien2k3/protocol/openid-connect/token}

cors:
  allowed-origins: "*"
